# CI [install -> build -> test]

name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_and_test_in_ubuntu_latest:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install lerna
      - name: install global dependencies
        run: npm i lerna && npm run install:app

      - name: Build app
        run: npm run build:app

      - name: run tests
        run: npm run test:app

  build_and_test_in_windows_latest:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install lerna
      - name: install global dependencies
        run: npm i lerna && npm run install:app

      - name: Build app
        run: npm run build:app

      - name: run tests
        run: npm run test:app
